// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE3ab7953DecodeDbforumDomainEntity(in *jlexer.Lexer, out *StatsInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			out.UsersCount = int(in.Int())
		case "forum":
			out.ForumsCount = int(in.Int())
		case "thread":
			out.ThreadsCount = int(in.Int())
		case "post":
			out.PostsCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeDbforumDomainEntity(out *jwriter.Writer, in StatsInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UsersCount))
	}
	{
		const prefix string = ",\"forum\":"
		out.RawString(prefix)
		out.Int(int(in.ForumsCount))
	}
	{
		const prefix string = ",\"thread\":"
		out.RawString(prefix)
		out.Int(int(in.ThreadsCount))
	}
	{
		const prefix string = ",\"post\":"
		out.RawString(prefix)
		out.Int(int(in.PostsCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeDbforumDomainEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeDbforumDomainEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeDbforumDomainEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeDbforumDomainEntity(l, v)
}
